 # Lab Number One - Analysis of City of Seattle Wage Data

 ## David Abramowitz
### AUG27, 2018

## Abstract

In this lab, the data on the salaries of all employees of the City of Seattle was examined with the goal of finding who earns the most, the least, and what the average salary is. The mean salary was found to be $39.59 per hour. The lowest wage is $5.53 and highest is $137.79 per hour (rounded). 

## Dataset Preparation

The first thing that was done to the data was seperating wage information from title and name information. After that, the mean salary was found. Also, the lowest and highest wages in the data were found; there corresponding names and titles were also found. This dataset represents the salary of every individual on the city government's payroll.

After the data was stored in an empty list, this is what happened to the data:
- The data was split into two lists, one for wages and the other for names and titles
- The average salary was found
- The minimum and maximun salaries were found
- These minimums and maximums were then associated with their corresponding names and titles

In [46]:
#open the file
data_file = open("Simplified_City_of_Seattle_Wage_Data.csv", "r");

#make an empty list to store the wage data
wage_list = [];

#put all of the lines from the CSV file in our list
for row in data_file:
    wage_list.append(row);
    
#close the file
data_file.close();

#check that the file was read into the list properly
print(wage_list[:5])
    
    

['Hourly Rate,Employee: First Name Last Name  Job Title: Job Title  Department: Department\n', '53.79,Employee: Leslie Kennedy  Job Title: StratAdvsr2 General Govt  Department: Finance & Admin Services Dept\n', '51.574,Employee: Christina Johnson  Job Title: StratAdvsr2 General Govt  Department: Finance & Admin Services Dept\n', '54.84,Employee: Michael Johnson  Job Title: StratAdvsr2 General Govt  Department: Finance & Admin Services Dept\n', '25.54,Employee: Michael Mustello  Job Title: Cust Svc Rep  Department: Finance & Admin Services Dept\n']


Description of splitting the data

In [47]:
#remove the column header from wage list
del wage_list[0];

#create empty lists for salary and name information
salary_list = [];
name_list = [];
for item in range(len(wage_list)):
    #split the item into two parts and insert into original list
    wage_list[item] = wage_list[item].split(",")
    
    #add the two items to the seperate salary and name lists
    salary_list.append(float((wage_list[item][0]))) 
    name_list.append(wage_list[item][1])
#Check that lists were split correctly   
print(salary_list[:5])
print(name_list[:5])

[53.79, 51.574, 54.84, 25.54, 27.49]
['Employee: Leslie Kennedy  Job Title: StratAdvsr2 General Govt  Department: Finance & Admin Services Dept\n', 'Employee: Christina Johnson  Job Title: StratAdvsr2 General Govt  Department: Finance & Admin Services Dept\n', 'Employee: Michael Johnson  Job Title: StratAdvsr2 General Govt  Department: Finance & Admin Services Dept\n', 'Employee: Michael Mustello  Job Title: Cust Svc Rep  Department: Finance & Admin Services Dept\n', 'Employee: Sokleng Kin  Job Title: Cust Svc Rep Sr  Department: Finance & Admin Services Dept\n']


In [48]:
#Finding average of all salaries in the list
count = len(salary_list)
print("Total number of employees", count)
total = sum(salary_list)
print("Total amount of hourly wages paid to city employees", total)
average=total/count
print("Average salary of city employees", average)

Total number of employees 12934
Total amount of hourly wages paid to city employees 511992.64519999747
Average salary of city employees 39.58501973094151


In [49]:
#Finding the min and max salaries (one of the lowest employees is...)
min_salary = min(salary_list)
max_salary = max(salary_list)
print("min salary is ", min_salary, " max salary is ", max_salary  )

#Finding corresponding names
min_index = salary_list.index(min_salary)
print(name_list[min_index])
max_index = salary_list.index(max_salary)
print(name_list[max_index])

min salary is  5.53  max salary is  137.788
Employee: Amy Bonfrisco  Job Title: Civil Svc Commissioner  Department: Civil Service Commissions Dept

Employee: Mami Hara  Job Title: SPU General Mgr&CEO  Department: Seattle Public Utilities



## Data Modeling

The nature of this lab was such that no modeling would be done. 

## Analysis and Conclusion

The mean salary for the city of Seattle has been found to be 39.59 dollars per hour. We also found that the lowest earning employee in the City of Seattle payroll is Amy Bonfrisco who earns 5.53 dollars an hour, and the highest earning employee is Mami Hara who earns 137.79 dollars per hour. These values have been rounded to the nearest hundredth. Areas for further exploration include other employees who have the same salary, why the mayor does not have the highest salary, what about being the role of GM and CEO of SPU makes it such a lucrative position (one possible theory is retention concerns between the public and private sectors). Also, how is wage of less than the federal minimum wage of $7.25 per hour possible? What about that specific position allows for a well below minimum wage?

## Acknowledgements

All of the code found in "Dataset Preparation" came from Ms. Sconyers. She also provided help in simplifying the dataset and assisted with the written content of the lab. Also, this work could not have been possible had the City of Seattle not published the data on their employees.  